/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
    "/api/user/register": {
        /** 注册用户 */
        post: {
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                    "text/json": components["schemas"]["RegisterRequest"];
                    "application/*+json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    content: never;
                };
                /** @description Bad Request */
                400: {
                    content: {
                        "text/plain": components["schemas"]["ExceptionMessage"];
                        "application/json": components["schemas"]["ExceptionMessage"];
                        "text/json": components["schemas"]["ExceptionMessage"];
                    };
                };
            };
        };
    };
    "/api/user/login": {
        /** 用户登录 */
        post: {
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                    "text/json": components["schemas"]["LoginRequest"];
                    "application/*+json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    content: {
                        "text/plain": components["schemas"]["LoginResponse"];
                        "application/json": components["schemas"]["LoginResponse"];
                        "text/json": components["schemas"]["LoginResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    content: {
                        "text/plain": components["schemas"]["ExceptionMessage"];
                        "application/json": components["schemas"]["ExceptionMessage"];
                        "text/json": components["schemas"]["ExceptionMessage"];
                    };
                };
            };
        };
    };
    "/api/user/{userId}": {
        /** 获得用户信息 */
        get: {
            parameters: {
                path: {
                    userId: string;
                };
            };
            responses: {
                /** @description Success */
                200: {
                    content: {
                        "text/plain": components["schemas"]["UserResponse"];
                        "application/json": components["schemas"]["UserResponse"];
                        "text/json": components["schemas"]["UserResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    content: never;
                };
                /** @description Forbidden */
                403: {
                    content: never;
                };
            };
        };
        /** 修改用户信息 */
        put: {
            parameters: {
                path: {
                    userId: string;
                };
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                    "text/json": components["schemas"]["UserResponse"];
                    "application/*+json": components["schemas"]["UserResponse"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    content: {
                        "text/plain": components["schemas"]["UserResponse"];
                        "application/json": components["schemas"]["UserResponse"];
                        "text/json": components["schemas"]["UserResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    content: {
                        "text/plain": components["schemas"]["ExceptionMessage"];
                        "application/json": components["schemas"]["ExceptionMessage"];
                        "text/json": components["schemas"]["ExceptionMessage"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    content: never;
                };
                /** @description Forbidden */
                403: {
                    content: never;
                };
            };
        };
    };
    "/api/user/all": {
        /** 获得所有的用户信息 */
        get: {
            responses: {
                /** @description Success */
                200: {
                    content: {
                        "text/plain": components["schemas"]["UserResponse"][];
                        "application/json": components["schemas"]["UserResponse"][];
                        "text/json": components["schemas"]["UserResponse"][];
                    };
                };
                /** @description Unauthorized */
                401: {
                    content: never;
                };
                /** @description Forbidden */
                403: {
                    content: never;
                };
            };
        };
    };
}

export type webhooks = Record<string, never>;

export interface components {
    schemas: {
        /** @description 错误信息传输类 */
        ExceptionMessage: {
            /** @description 错误信息 */
            message: string;
        };
        /** @description 用户登录请求的传输类 */
        LoginRequest: {
            /** @description 需要登录的用户ID */
            id: string;
            /** @description 登录用户的密码 */
            password: string;
        };
        /** @description 用户登录信息的传输类 */
        LoginResponse: {
            /** @description 登录成功之后生成的令牌 */
            token: string;
        };
        /** @description 用户权限信息的传输类 */
        PermissionResponse: {
            /** @description 用户是否为超级管理员 */
            sudo: boolean;
            /** @description 用户是否为客房管理员 */
            roomAdmin: boolean;
            /** @description 用户是否为空调管理员 */
            airconAdmin: boolean;
            /** @description 用户是否为账单管理员 */
            billAdmin: boolean;
        };
        /** @description 注册的请求信息传输类 */
        RegisterRequest: {
            /** @description 用户ID */
            id: string;
            /** @description 用户名 */
            name: string;
            /** @description 用户密码 */
            password: string;
        };
        /** @description 用户信息传输类 */
        UserResponse: {
            /** @description 用户ID */
            id: string;
            /** @description 用户名 */
            name: string;
            auth: components["schemas"]["PermissionResponse"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
